const state={photos:[],html:''};const $=id=>document.getElementById(id),fileInput=$('fileInput');
fileInput.addEventListener('change',e=>addFiles([...e.target.files]));$('dropzone').addEventListener('dragover',e=>e.preventDefault());$('dropzone').addEventListener('drop',e=>{e.preventDefault();addFiles([...e.dataTransfer.files])});
function addFiles(files){state.photos.push(...files.filter(f=>f.type.startsWith('image/')).map(file=>({file,url:URL.createObjectURL(file),name:file.name})));renderPhotos()}
function renderPhotos(){$('photoCount').textContent=`${state.photos.length}장`;$('photoGrid').innerHTML=state.photos.map((p,i)=>`<div class="thumb"><img src="${p.url}" alt="${p.name}"><button onclick="removePhoto(${i})">×</button></div>`).join('')}
window.removePhoto=i=>{URL.revokeObjectURL(state.photos[i].url);state.photos.splice(i,1);renderPhotos()};$('demoBtn').onclick=()=>{$('place').value='교토 기요미즈데라';$('memo').value='언덕길을 올라 만난 오래된 목조 무대와 도시 풍경이 인상적이었다.';if(!state.photos.length)$('fileInput').click()};
async function dataUrl(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
$('deepSeekBtn').onclick=async()=>{if(!state.photos.length){alert('사진을 먼저 올려주세요.');return}const b=$('deepSeekBtn');b.disabled=true;b.textContent='분석 중…';try{const images=await Promise.all(state.photos.map(p=>dataUrl(p.file)));const r=await fetch('/api/deepseek',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:buildPrompt(),images})});const d=await r.json();if(!r.ok)throw Error(d.error||'분석에 실패했습니다.');state.html=d.choices?.[0]?.message?.content||'';$('chatGptResult').value=state.html;$('preview').classList.remove('hidden');$('previewBtn').click()}catch(e){alert(e.message+'\n로컬 서버가 실행 중인지 확인하세요.')}finally{b.disabled=false;b.innerHTML='AI로 사진 분석·글쓰기 <span>→</span>'}};
function buildPrompt(){const list=state.photos.map((p,i)=>`P${String(i+1).padStart(3,'0')}: ${p.name}`).join('\n');return `여행지: ${$('place').value||'미확인'}\n방문 날짜: ${$('date').value||'미기재'}\n글 분위기: ${$('tone').value}\n여행 메모: ${$('memo').value||'없음'}\n사진 목록:\n${list}\n\n사진 속 장소와 대상을 분석하고, 비슷한 사진은 잘 나온 1~3장만 선별하며 서로 다른 장면은 유지해줘. 사진 제목, 역사·문화·사회적 의미·가이드 이야기·일화를 포함해줘. 사실·추정·전설을 구분해줘. 특정 블로거를 모방하지 말고 짧은 문단과 인용문을 활용해줘. 최종 출력은 사진 분석 요약, 비슷한 사진 선별, 사진별 제목, 블로그 제목 3개, 원고, 네이버·티스토리용 단순 HTML, 사실·추정·전설, 출처 순서로 작성해줘. HTML에는 가짜 이미지 URL 대신 [사진: 사진 제목] 또는 [슬라이드: 제목1 / 제목2]를 사용해줘.`}
$('previewBtn').onclick=()=>{$('article').innerHTML=$('chatGptResult').value.trim()||'<p>생성된 글이 여기에 표시됩니다.</p>';$('preview').scrollIntoView({behavior:'smooth'})};$('copyBtn').onclick=async()=>{await navigator.clipboard.writeText($('chatGptResult').value);$('copyBtn').textContent='복사 완료';setTimeout(()=>$('copyBtn').textContent='HTML 복사',1500)};$('downloadBtn').onclick=()=>{const blob=new Blob([$('chatGptResult').value],{type:'text/html;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='triptail-blog.html';a.click()};
